<mygridlayout>
    GridLayout:
        cols:1
        size:root.width,root.height
        GridLayout:
            cols:2
            Label:
                text:"name"
            TextInput:
                multiline:True
            
            Label:
                text:"rollno"
            TextInput:
                multiline:True
                
            Label:
                text:"class"
            TextInput:
                multiline:True
        Button:
            text: "Submit"